### ISSUE TITLE
Summary/checklist of issues in 13 May telecon

### ISSUE THREAD

**Issue by willettk** [willettk/gzhubble#94]
- [x] Need to add some interpretation of Figure 12 - comparison with other surveys. 
- [ ] @karenlmasters: a little bit of this in @melvin6100 thesis, worth having a look at that work which has been done. 
- [x] @claudiascarlata: M<23.5 only should be used, z<1 also. 
- [x] @chrislintott: we should split parametric techniques and expert classifications. 
- [ ] @karenlmasters: look at Sheth bar IDs. 
- [x] @willettk: Lots of different techniques here. How much comparison? 
- [x] @karenlmasters: more details on the figure/methods used. 
- [x] @chrislintott: think figure should be split up. 

Method for comments: pull request of rewrites is fine, but can be challenging at times. 
Small changes in a pull request also fine, but lots in a single pull request isn’t great.  
@bamford gave some github advice I couldn’t understand (because of audio problems).

**Comment by bamford** [comment]
In case it is useful, what I said was:
http://stackoverflow.com/a/10037780/1840212
with a pinch of:
http://www.nickcoding.com/2014/10/30/making-git-prose-friendly/

**Comment by bamford** [comment]
... but I think issues with task lists seem easier to manage.
